source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.5'

inhibit_all_warnings!
install! 'cocoapods', :disable_input_output_paths => true

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'slark', :path => '../../..' 
end


