source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

inhibit_all_warnings!
install! 'cocoapods', :disable_input_output_paths => true

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'slark', :path => '../../../script/slark.podspec' 
end