language: cpp
dist: focal
sudo: required

jobs:
    include:
        -   os: linux
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-17
                    packages:
                        - cmake
                        - clang-17
                        - wget
            env:
                - MATRIX_EVAL="CC=clang-17 && CXX=clang++-17"
            arch: amd64
            compiler: clang

        -   os: osx
            osx_image: xcode15.0

before_install:
    - eval "${MATRIX_EVAL}"
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install clang-17; fi

branches:
    - main
    - develop

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake -G "Unix Makefiles" .
    - make -j 4
