# CMake generated Testfile for 
# Source directory: /Users/rolf.tan/selfspace/slark/test/base_test
# Build directory: /Users/rolf.tan/selfspace/slark/script/test/base_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[equal.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=equal.CTime")
  set_tests_properties([=[equal.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[equal.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=equal.CTime")
  set_tests_properties([=[equal.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[equal.CTime]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=equal.CTime")
  set_tests_properties([=[equal.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[equal.CTime]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=equal.CTime")
  set_tests_properties([=[equal.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[equal.CTime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[add.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=add.CTime")
  set_tests_properties([=[add.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[add.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=add.CTime")
  set_tests_properties([=[add.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[add.CTime]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=add.CTime")
  set_tests_properties([=[add.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[add.CTime]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=add.CTime")
  set_tests_properties([=[add.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[add.CTime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[sub.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=sub.CTime")
  set_tests_properties([=[sub.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[sub.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=sub.CTime")
  set_tests_properties([=[sub.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[sub.CTime]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=sub.CTime")
  set_tests_properties([=[sub.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[sub.CTime]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=sub.CTime")
  set_tests_properties([=[sub.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[sub.CTime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[less.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=less.CTime")
  set_tests_properties([=[less.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[less.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=less.CTime")
  set_tests_properties([=[less.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[less.CTime]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=less.CTime")
  set_tests_properties([=[less.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[less.CTime]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=less.CTime")
  set_tests_properties([=[less.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[less.CTime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gerater.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=gerater.CTime")
  set_tests_properties([=[gerater.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gerater.CTime]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=gerater.CTime")
  set_tests_properties([=[gerater.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gerater.CTime]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=gerater.CTime")
  set_tests_properties([=[gerater.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gerater.CTime]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=gerater.CTime")
  set_tests_properties([=[gerater.CTime]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[gerater.CTime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[equal.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=equal.CTimeRange")
  set_tests_properties([=[equal.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[equal.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=equal.CTimeRange")
  set_tests_properties([=[equal.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[equal.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=equal.CTimeRange")
  set_tests_properties([=[equal.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[equal.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=equal.CTimeRange")
  set_tests_properties([=[equal.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[equal.CTimeRange]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[overloop.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=overloop.CTimeRange")
  set_tests_properties([=[overloop.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[overloop.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=overloop.CTimeRange")
  set_tests_properties([=[overloop.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[overloop.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=overloop.CTimeRange")
  set_tests_properties([=[overloop.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[overloop.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=overloop.CTimeRange")
  set_tests_properties([=[overloop.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[overloop.CTimeRange]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[less.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/Debug/base_test" "--gtest_filter=less.CTimeRange")
  set_tests_properties([=[less.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[less.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/Release/base_test" "--gtest_filter=less.CTimeRange")
  set_tests_properties([=[less.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[less.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/MinSizeRel/base_test" "--gtest_filter=less.CTimeRange")
  set_tests_properties([=[less.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[less.CTimeRange]=] "/Users/rolf.tan/selfspace/slark/build/RelWithDebInfo/base_test" "--gtest_filter=less.CTimeRange")
  set_tests_properties([=[less.CTimeRange]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;14;gtest_add_tests;/Users/rolf.tan/selfspace/slark/test/base-test/CMakeLists.txt;0;")
else()
  add_test([=[less.CTimeRange]=] NOT_AVAILABLE)
endif()
